### ISSUE TITLE
npx esbuild-azure-functions fails

### ISSUE THREAD

**Issue by philzartis** [beyerleinf/esbuild-azure-functions#9]
First and foremost, thanks for this library 🤗 

On node 16 on Windows running `npx esbuild-azure-functions` (via fish-shell on git-bash) just opens the `node_modules/esbuild-azure-functions/build/src/cli.js` file with the default editor, and in GH Actions it fails to execute, throwing this error:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/49065724/184603322-67c6b0c9-fca7-43c5-8108-92851852e756.png">

I fixed my local build by mimicking other files in the bin folder (example below showing cmd comparison with rimraf, changes are highlighted):
![image](https://user-images.githubusercontent.com/49065724/184606080-824127a1-c4b4-42ca-8330-d0efa32fc69e.png)

Assuming there's a missing shebang line in cli file. The above is for release v1.1.1.

**Comment by beyerleinf** [comment]
Hi, thanks for reporting this! I'm going to test this (and your fix) out later tonight. Unless this is super urgent for you?

**Comment by philzartis** [comment]
Much appreciated. Not urgent at all! Let me know if I can help in any way :)

**Comment by beyerleinf** [comment]
@philzartis Can you please test version `1.1.2-test` and let me know if it fixed your issue?

**Comment by philzartis** [comment]
I can confirm that the issue is fixed. The generated bin files for windows (cmd & ps2) also have a different structure now (I wish npm documented this magical behavior clearer).
Thanks Fabian! 💪

**Comment by beyerleinf** [comment]
Very interesting. I'm going the publish the proper version later and let you know :)

**Comment by beyerleinf** [comment]
Just published `v.1.1.2`
